# Generated by Django 4.2.27 on 2025-12-16 10:04

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('calculation_period', models.CharField(help_text='Месяц, сезон, год и др.', max_length=50, verbose_name='Период расчёта')),
                ('total_pdre', models.FloatField(verbose_name='Общая ПДРЕ ООПТ (чел/ед.времени)')),
                ('area_pdre', models.JSONField(default=dict, help_text='Словарь с распределением ПДРЕ по участкам', verbose_name='ПДРЕ по участкам')),
                ('calculation_details', models.JSONField(default=dict, help_text='Подробная информация о каждом этапе расчёта', verbose_name='Детали расчёта')),
                ('input_parameters', models.JSONField(default=dict, help_text='Использованные параметры расчёта', verbose_name='Входные параметры')),
                ('heatmap_data', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326, verbose_name='Тепловая карта нагрузки')),
                ('visualization_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на визуализацию')),
                ('calculation_status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='completed', max_length=50, verbose_name='Статус расчёта')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Результат расчёта ПДРЕ',
                'verbose_name_plural': 'Результаты расчётов ПДРЕ',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='LimitingFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование фактора')),
                ('factor_type', models.CharField(choices=[('ecological', 'Экологический'), ('social', 'Социальный'), ('cultural', 'Социокультурный'), ('infrastructure', 'Инфраструктурный')], max_length=50, verbose_name='Тип фактора')),
                ('description', models.TextField(verbose_name='Описание')),
                ('coefficient_value', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Значение коэффициента')),
                ('calculation_formula', models.TextField(blank=True, null=True, verbose_name='Формула расчёта')),
                ('apply_to_all', models.BooleanField(default=True, verbose_name='Применять ко всем ООПТ')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Зона влияния фактора', null=True, srid=4326, verbose_name='Геометрия влияния')),
            ],
            options={
                'verbose_name': 'Лимитирующий фактор',
                'verbose_name_plural': 'Лимитирующие факторы',
            },
        ),
        migrations.CreateModel(
            name='PDREParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('slope', 'Уклон территории'), ('vegetation_density', 'Плотность растительности'), ('soil_erosion', 'Эрозионная опасность'), ('fire_hazard', 'Пожарная опасность'), ('wetlands', 'Увлажнённость'), ('infrastructure', 'Близость инфраструктуры'), ('anthropogenic', 'Антропогенная нагрузка')], max_length=50, verbose_name='Тип параметра')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('raster_data', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326, verbose_name='Растровые данные')),
                ('vector_zones', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326, verbose_name='Векторные зоны')),
                ('value_range', models.JSONField(default=dict, help_text="{'min': 0, 'max': 1, 'mean': 0.5}", verbose_name='Диапазон значений')),
                ('data_source', models.CharField(max_length=200, verbose_name='Источник данных')),
                ('processing_method', models.CharField(blank=True, max_length=200, null=True, verbose_name='Метод обработки')),
            ],
            options={
                'verbose_name': 'Параметр территории',
                'verbose_name_plural': 'Параметры территории',
            },
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('area_type', models.CharField(choices=[('federal', 'Федеральная'), ('regional', 'Региональная'), ('local', 'Местная')], max_length=50, verbose_name='Тип ООПТ')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Границы')),
                ('cadastral_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кадастровый номер')),
                ('area_ha', models.FloatField(editable=False, verbose_name='Площадь (га)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('pdre_value', models.FloatField(blank=True, null=True, verbose_name='ПДРЕ ООПТ (чел/ед.времени)')),
                ('calculation_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод расчёта')),
                ('calculation_parameters', models.JSONField(default=dict, verbose_name='Параметры расчёта')),
            ],
            options={
                'verbose_name': 'ООПТ',
                'verbose_name_plural': 'ООПТ',
            },
        ),
        migrations.CreateModel(
            name='TourismPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('valid_until', models.DateField(verbose_name='Действителен до')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия')),
                ('executive_summary', models.TextField(verbose_name='Краткое резюме')),
                ('methodology_description', models.TextField(verbose_name='Описание методики')),
                ('calculation_results', models.TextField(verbose_name='Результаты расчёта')),
                ('recommendations', models.TextField(verbose_name='Рекомендации')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='passport_maps/', verbose_name='Карта')),
                ('charts_data', models.JSONField(default=dict, verbose_name='Данные для графиков')),
                ('document_file', models.FileField(upload_to='passport_documents/', verbose_name='Файл паспорта (PDF)')),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Утверждён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('protected_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='pdre_calculation.protectedarea', verbose_name='ООПТ')),
            ],
            options={
                'verbose_name': 'Паспорт территории',
                'verbose_name_plural': 'Паспорта территорий',
            },
        ),
        migrations.CreateModel(
            name='TourismObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('object_type', models.CharField(choices=[('areal', 'Площадной объект'), ('linear', 'Линейный объект (маршрут)'), ('point', 'Точечный объект')], max_length=50, verbose_name='Тип объекта')),
                ('tourism_type', models.CharField(choices=[('day_trip', 'Однодневный маршрут'), ('multi_day', 'Многодневный маршрут'), ('autonomous', 'Автономный многодневный маршрут'), ('facility', 'Объект инфраструктуры')], max_length=50, verbose_name='Тип туризма')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Геометрия')),
                ('area_sq_m', models.FloatField(blank=True, null=True, verbose_name='Площадь объекта (кв. м)')),
                ('length_km', models.FloatField(blank=True, null=True, verbose_name='Длина маршрута (км)')),
                ('area_per_visitor', models.FloatField(default=10.0, help_text='Согласно п.18 методики', verbose_name='Площадь на одного посетителя (кв. м)')),
                ('operating_hours', models.FloatField(default=8.0, verbose_name='Время доступности объекта (часов в сутки)')),
                ('avg_visit_duration', models.FloatField(default=2.0, verbose_name='Среднее время посещения (часов)')),
                ('avg_group_size', models.FloatField(default=3.0, verbose_name='Средний размер группы (чел.)')),
                ('return_factor', models.FloatField(blank=True, null=True, verbose_name='Коэффициент возвращения')),
                ('base_capacity', models.FloatField(blank=True, null=True, verbose_name='Базовая емкость (BCC)')),
                ('potential_capacity', models.FloatField(blank=True, null=True, verbose_name='Потенциальная емкость (PCC)')),
                ('pdre_capacity', models.FloatField(blank=True, null=True, verbose_name='ПДРЕ объекта (RCC)')),
                ('correction_factors', models.JSONField(default=dict, help_text='Словарь с коэффициентами Cf1, Cf2, ... и дополнительными параметрами', verbose_name='Поправочные коэффициенты')),
                ('management_factor', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коэффициент управленческой емкости (MC)')),
                ('data_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='Источник данных')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('protected_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourism_objects', to='pdre_calculation.protectedarea', verbose_name='ООПТ')),
            ],
            options={
                'verbose_name': 'Туристский объект',
                'verbose_name_plural': 'Туристские объекты',
            },
        ),
        migrations.AddIndex(
            model_name='protectedarea',
            index=models.Index(fields=['boundary'], name='pdre_calcul_boundar_818442_idx'),
        ),
        migrations.AddField(
            model_name='pdreparameter',
            name='protected_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='pdre_calculation.protectedarea', verbose_name='ООПТ'),
        ),
        migrations.AddField(
            model_name='limitingfactor',
            name='protected_areas',
            field=models.ManyToManyField(blank=True, to='pdre_calculation.protectedarea', verbose_name='ООПТ для применения'),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='protected_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='pdre_calculation.protectedarea', verbose_name='ООПТ'),
        ),
        migrations.AddIndex(
            model_name='tourismobject',
            index=models.Index(fields=['geometry'], name='pdre_calcul_geometr_42e866_idx'),
        ),
        migrations.AddIndex(
            model_name='tourismobject',
            index=models.Index(fields=['protected_area', 'object_type'], name='pdre_calcul_protect_76dc84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pdreparameter',
            unique_together={('protected_area', 'parameter_type')},
        ),
    ]
